package org.framework42.utils.services;

public interface ASCII7Util {

    public static final byte    X_FF                  = -1;
    public static final byte    X_FE                  = -2;
    public static final byte    X_FD                  = -3;
    public static final byte    X_FC                  = -4;
    public static final byte    X_FB                  = -5;
    public static final byte    X_FA                  = -6;
    public static final byte    X_F9                  = -7;
    public static final byte    X_F8                  = -8;
    public static final byte    X_F7                  = -9;
    public static final byte    X_F6                  = -10;
    public static final byte    X_F5                  = -11;
    public static final byte    X_F4                  = -12;
    public static final byte    X_F3                  = -13;
    public static final byte    X_F2                  = -14;
    public static final byte    X_F1                  = -15;
    public static final byte    X_F0                  = -16;

    public static final byte    X_EF                  = -17;
    public static final byte    X_EE                  = -18;
    public static final byte    X_ED                  = -19;
    public static final byte    X_EC                  = -20;
    public static final byte    X_EB                  = -21;
    public static final byte    X_EA                  = -22;
    public static final byte    X_E9                  = -23;
    public static final byte    X_E8                  = -24;
    public static final byte    X_E7                  = -25;
    public static final byte    X_E6                  = -26;
    public static final byte    X_E5                  = -27;
    public static final byte    X_E4                  = -28;
    public static final byte    X_E3                  = -29;
    public static final byte    X_E2                  = -30;
    public static final byte    X_E1                  = -31;
    public static final byte    X_E0                  = -32;

    public static final byte    X_DF                  = -33;
    public static final byte    X_DE                  = -34;
    public static final byte    X_DD                  = -35;
    public static final byte    X_DC                  = -36;
    public static final byte    X_DB                  = -37;
    public static final byte    X_DA                  = -38;
    public static final byte    X_D9                  = -39;
    public static final byte    X_D8                  = -40;
    public static final byte    X_D7                  = -41;
    public static final byte    X_D6                  = -42;
    public static final byte    X_D5                  = -43;
    public static final byte    X_D4                  = -44;
    public static final byte    X_D3                  = -45;
    public static final byte    X_D2                  = -46;
    public static final byte    X_D1                  = -47;
    public static final byte    X_D0                  = -48;

    public static final byte    X_CF                  = -49;
    public static final byte    X_CE                  = -50;
    public static final byte    X_CD                  = -51;
    public static final byte    X_CC                  = -52;
    public static final byte    X_CB                  = -53;
    public static final byte    X_CA                  = -54;
    public static final byte    X_C9                  = -55;
    public static final byte    X_C8                  = -56;
    public static final byte    X_C7                  = -57;
    public static final byte    X_C6                  = -58;
    public static final byte    X_C5                  = -59;
    public static final byte    X_C4                  = -60;
    public static final byte    X_C3                  = -61;
    public static final byte    X_C2                  = -62;
    public static final byte    X_C1                  = -63;
    public static final byte    X_C0                  = -64;

    public static final byte    X_BF                  = -65;
    public static final byte    X_BE                  = -66;
    public static final byte    X_BD                  = -67;
    public static final byte    X_BC                  = -68;
    public static final byte    X_BB                  = -69;
    public static final byte    X_BA                  = -70;
    public static final byte    X_B9                  = -71;
    public static final byte    X_B8                  = -72;
    public static final byte    X_B7                  = -73;
    public static final byte    X_B6                  = -74;
    public static final byte    X_B5                  = -75;
    public static final byte    X_B4                  = -76;
    public static final byte    X_B3                  = -77;
    public static final byte    X_B2                  = -78;
    public static final byte    X_B1                  = -79;
    public static final byte    X_B0                  = -80;

    public static final byte    X_AF                  = -81;
    public static final byte    X_AE                  = -82;
    public static final byte    X_AD                  = -83;
    public static final byte    X_AC                  = -84;
    public static final byte    X_AB                  = -85;
    public static final byte    X_AA                  = -86;
    public static final byte    X_A9                  = -87;
    public static final byte    X_A8                  = -88;
    public static final byte    X_A7                  = -89;
    public static final byte    X_A6                  = -90;
    public static final byte    X_A5                  = -91;
    public static final byte    X_A4                  = -92;
    public static final byte    X_A3                  = -93;
    public static final byte    X_A2                  = -94;
    public static final byte    X_A1                  = -95;
    public static final byte    X_A0                  = -96;

    public static final byte    X_9F                  = -97;
    public static final byte    X_9E                  = -98;
    public static final byte    X_9D                  = -99;
    public static final byte    X_9C                  = -100;
    public static final byte    X_9B                  = -101;
    public static final byte    X_9A                  = -102;
    public static final byte    X_99                  = -103;
    public static final byte    X_98                  = -104;
    public static final byte    X_97                  = -105;
    public static final byte    X_96                  = -106;
    public static final byte    X_95                  = -107;
    public static final byte    X_94                  = -108;
    public static final byte    X_93                  = -109;
    public static final byte    X_92                  = -110;
    public static final byte    X_91                  = -111;
    public static final byte    X_90                  = -112;

    public static final byte    X_8F                  = -113;
    public static final byte    X_8E                  = -114;
    public static final byte    X_8D                  = -115;
    public static final byte    X_8C                  = -116;
    public static final byte    X_8B                  = -117;
    public static final byte    X_8A                  = -118;
    public static final byte    X_89                  = -119;
    public static final byte    X_88                  = -120;
    public static final byte    X_87                  = -121;
    public static final byte    X_86                  = -122;
    public static final byte    X_85                  = -123;
    public static final byte    X_84                  = -124;
    public static final byte    X_83                  = -125;
    public static final byte    X_82                  = -126;
    public static final byte    X_81                  = -127;
    public static final byte    X_80                  = -128;

    public static final byte    X_7F                  = 127;
    public static final byte    X_7E                  = 126;
    public static final byte    X_7D                  = 125;
    public static final byte    X_7C                  = 124;
    public static final byte    X_7B                  = 123;
    public static final byte    X_7A                  = 122;
    public static final byte    X_79                  = 121;
    public static final byte    X_78                  = 120;
    public static final byte    X_77                  = 119;
    public static final byte    X_76                  = 118;
    public static final byte    X_75                  = 117;
    public static final byte    X_74                  = 116;
    public static final byte    X_73                  = 115;
    public static final byte    X_72                  = 114;
    public static final byte    X_71                  = 113;
    public static final byte    X_70                  = 112;

    public static final byte    X_6F                  = 111;
    public static final byte    X_6E                  = 110;
    public static final byte    X_6D                  = 109;
    public static final byte    X_6C                  = 108;
    public static final byte    X_6B                  = 107;
    public static final byte    X_6A                  = 106;
    public static final byte    X_69                  = 105;
    public static final byte    X_68                  = 104;
    public static final byte    X_67                  = 103;
    public static final byte    X_66                  = 102;
    public static final byte    X_65                  = 101;
    public static final byte    X_64                  = 100;
    public static final byte    X_63                  = 99;
    public static final byte    X_62                  = 98;
    public static final byte    X_61                  = 97;
    public static final byte    X_60                  = 96;

    public static final byte    X_5F                  = 95;
    public static final byte    X_5E                  = 94;
    public static final byte    X_5D                  = 93;
    public static final byte    X_5C                  = 92;
    public static final byte    X_5B                  = 91;
    public static final byte    X_5A                  = 90;
    public static final byte    X_59                  = 89;
    public static final byte    X_58                  = 88;
    public static final byte    X_57                  = 87;
    public static final byte    X_56                  = 86;
    public static final byte    X_55                  = 85;
    public static final byte    X_54                  = 84;
    public static final byte    X_53                  = 83;
    public static final byte    X_52                  = 82;
    public static final byte    X_51                  = 81;
    public static final byte    X_50                  = 80;

    public static final byte    X_4F                  = 79;
    public static final byte    X_4E                  = 78;
    public static final byte    X_4D                  = 77;
    public static final byte    X_4C                  = 76;
    public static final byte    X_4B                  = 75;
    public static final byte    X_4A                  = 74;
    public static final byte    X_49                  = 73;
    public static final byte    X_48                  = 72;
    public static final byte    X_47                  = 71;
    public static final byte    X_46                  = 70;
    public static final byte    X_45                  = 69;
    public static final byte    X_44                  = 68;
    public static final byte    X_43                  = 67;
    public static final byte    X_42                  = 66;
    public static final byte    X_41                  = 65;
    public static final byte    X_40                  = 64;

    public static final byte    X_3F                  = 63;
    public static final byte    X_3E                  = 62;
    public static final byte    X_3D                  = 61;
    public static final byte    X_3C                  = 60;
    public static final byte    X_3B                  = 59;
    public static final byte    X_3A                  = 58;
    public static final byte    X_39                  = 57;
    public static final byte    X_38                  = 56;
    public static final byte    X_37                  = 55;
    public static final byte    X_36                  = 54;
    public static final byte    X_35                  = 53;
    public static final byte    X_34                  = 52;
    public static final byte    X_33                  = 51;
    public static final byte    X_32                  = 50;
    public static final byte    X_31                  = 49;
    public static final byte    X_30                  = 48;

    public static final byte    X_2F                  = 47;
    public static final byte    X_2E                  = 46;
    public static final byte    X_2D                  = 45;
    public static final byte    X_2C                  = 44;
    public static final byte    X_2B                  = 43;
    public static final byte    X_2A                  = 42;
    public static final byte    X_29                  = 41;
    public static final byte    X_28                  = 40;
    public static final byte    X_27                  = 39;
    public static final byte    X_26                  = 38;
    public static final byte    X_25                  = 37;
    public static final byte    X_24                  = 36;
    public static final byte    X_23                  = 35;
    public static final byte    X_22                  = 34;
    public static final byte    X_21                  = 33;
    public static final byte    X_20                  = 32;

    public static final byte    X_1F                  = 31;
    public static final byte    X_1E                  = 30;
    public static final byte    X_1D                  = 29;
    public static final byte    X_1C                  = 28;
    public static final byte    X_1B                  = 27;
    public static final byte    X_1A                  = 26;
    public static final byte    X_19                  = 25;
    public static final byte    X_18                  = 24;
    public static final byte    X_17                  = 23;
    public static final byte    X_16                  = 22;
    public static final byte    X_15                  = 21;
    public static final byte    X_14                  = 20;
    public static final byte    X_13                  = 19;
    public static final byte    X_12                  = 18;
    public static final byte    X_11                  = 17;
    public static final byte    X_10                  = 16;

    public static final byte    X_0F                  = 15;
    public static final byte    X_0E                  = 14;
    public static final byte    X_0D                  = 13;
    public static final byte    X_0C                  = 12;
    public static final byte    X_0B                  = 11;
    public static final byte    X_0A                  = 10;
    public static final byte    X_09                  = 9;
    public static final byte    X_08                  = 8;
    public static final byte    X_07                  = 7;
    public static final byte    X_06                  = 6;
    public static final byte    X_05                  = 5;
    public static final byte    X_04                  = 4;
    public static final byte    X_03                  = 3;
    public static final byte    X_02                  = 2;
    public static final byte    X_01                  = 1;
    public static final byte    X_00                  = 0;

    public byte[] characterNormalisation(String data);

    public byte[] hexNormalisation(String hexData);

    public byte getHexAsByte(String hexValue);

    public String getValueAsHex(byte byteValue);

}
