
package uc_webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UCOrderService", targetNamespace = "http://webservices.uc.se/UCOrders/", wsdlLocation = "file:///home/fredrik/Documents/dev/banksystem/external_resources/UCOrders.wsdl")
public class UCOrderService
    extends Service
{

    private final static URL UCORDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uc_webservice.UCOrderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = uc_webservice.UCOrderService.class.getResource(".");
            url = new URL(baseUrl, "file:///home/fredrik/Documents/dev/banksystem/external_resources/UCOrders.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:///home/fredrik/Documents/dev/banksystem/external_resources/UCOrders.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        UCORDERSERVICE_WSDL_LOCATION = url;
    }

    public UCOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UCOrderService() {
        super(UCORDERSERVICE_WSDL_LOCATION, new QName("http://webservices.uc.se/UCOrders/", "UCOrderService"));
    }

    /**
     * 
     * @return
     *     returns UcOrders
     */
    @WebEndpoint(name = "ucOrders2")
    public UcOrders getUcOrders2() {
        return super.getPort(new QName("http://webservices.uc.se/UCOrders/", "ucOrders2"), UcOrders.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UcOrders
     */
    @WebEndpoint(name = "ucOrders2")
    public UcOrders getUcOrders2(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.uc.se/UCOrders/", "ucOrders2"), UcOrders.class, features);
    }

}
