<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5. --><wsdl:definitions xmlns:s1="http://www.uc.se/schemas/ucOrderReply/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s0="http://www.uc.se/schemas/ucOrderRequest/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://webservices.uc.se/UCOrders/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://webservices.uc.se/UCOrders/" groupName="UCOrders">

  <!-- version 2.2.2 -->
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ucOrderRequest="http://www.uc.se/schemas/ucOrderRequest/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://www.uc.se/schemas/ucOrderRequest/">

      <!-- main (root) elements that are used by the WSDL of the Web Service -->
      <xsd:element groupName="businessReport">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
            <xsd:element groupName="repositoryaction" type="ucOrderRequest:repositoryaction" minOccurs="0" maxOccurs="1"/>
            <xsd:element groupName="businessReportQuery" type="ucOrderRequest:reportQuery" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="product" type="ucOrderRequest:businessProduct" use="required"/>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="companyReport">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
            <xsd:element groupName="repositoryaction" type="ucOrderRequest:repositoryaction" minOccurs="0" maxOccurs="1"/>
            <xsd:element groupName="companyReportQuery" type="ucOrderRequest:reportQuery" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="product" type="ucOrderRequest:companyProduct" use="required"/>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="individualReport">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
            <xsd:element groupName="repositoryaction" type="ucOrderRequest:repositoryaction" minOccurs="0" maxOccurs="1"/>
            <xsd:element groupName="individualReportQuery" type="ucOrderRequest:reportQuery" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="product" type="ucOrderRequest:individualProduct" use="required"/>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="identityCheck">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="identifier" type="ucOrderRequest:objectRef" use="required"/>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
          <xsd:attribute groupName="worksites" type="xsd:boolean" use="optional"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="identitySeekFys">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
            <xsd:element groupName="seekFysiker" type="ucOrderRequest:seekFysiker" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="identifier" type="ucOrderRequest:objectRef" use="required"/>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="identitySeekJur">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
            <xsd:element groupName="seekJuridiker" type="ucOrderRequest:seekJuridiker" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="identifier" type="ucOrderRequest:objectRef" use="required"/>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="retrieveLagomReport">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="datastoreid" type="ucOrderRequest:lagomDatastoreId" use="required"/>
          <xsd:attribute groupName="objectid" type="ucOrderRequest:objectRef" use="required"/>
          <xsd:attribute groupName="sequenceNr" type="ucOrderRequest:lagomSequenceNr" use="required"/>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="retrieveAnnualReport">
        <xsd:complexType>
          <xsd:sequence minOccurs="1">
            <xsd:element groupName="customer" type="ucOrderRequest:customer" minOccurs="1" maxOccurs="1"/>
            <xsd:element groupName="retrieveAction" type="ucOrderRequest:retrieveAction" minOccurs="1" maxOccurs="1"/>
            <xsd:element groupName="annualQuery" type="ucOrderRequest:annualQuery" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="version" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>
      
  	  <xsd:element groupName="ping">
		<xsd:complexType>
			<xsd:attribute groupName="lang" type="ucOrderRequest:language" use="optional"/>
        	<xsd:attribute groupName="version" type="xsd:string" use="optional"/>
		</xsd:complexType>
 	 </xsd:element>

      <!-- Simple types for this schema -->

      <xsd:simpleType groupName="amount">
        <xsd:restriction base="xsd:int">
          <xsd:totalDigits value="18"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="income">
        <xsd:restriction base="ucOrderRequest:amount"/>
      </xsd:simpleType>

      <xsd:simpleType groupName="creditseekAmount">
        <xsd:restriction base="ucOrderRequest:amount">
          <xsd:totalDigits value="8"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="objectRef1">
        <xsd:restriction base="xsd:int">
          <xsd:totalDigits value="18"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="objectRef">
        <xsd:restriction base="xsd:string">
          <xsd:pattern value="\d{6}-\d{4}|\d{10}"/>
          <xsd:maxLength value="11"/>
          <xsd:minLength value="10"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="annualReportYear">
        <xsd:restriction base="xsd:string">
          <xsd:pattern value="[0-9]{4}"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="userId">
        <xsd:restriction base="xsd:string">
          <xsd:minLength value="5"/>
          <xsd:maxLength value="5"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="nameBase">
        <xsd:restriction base="xsd:string">
          <xsd:minLength value="1"/>
          <xsd:maxLength value="80"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="templateName">
        <xsd:restriction base="ucOrderRequest:nameBase">
          <xsd:maxLength value="3"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="groupName">
        <xsd:restriction base="ucOrderRequest:nameBase">
          <xsd:maxLength value="48"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="seekName">
        <xsd:restriction base="ucOrderRequest:nameBase">
          <xsd:maxLength value="48"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="referenceName">
        <xsd:restriction base="ucOrderRequest:nameBase">
          <xsd:maxLength value="32"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="orderedbyName">
        <xsd:restriction base="ucOrderRequest:nameBase">
          <xsd:maxLength value="64"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="emailName">
        <xsd:restriction base="ucOrderRequest:nameBase">
          <xsd:maxLength value="64"/>
          <xsd:pattern value=".*@.*"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="password">
        <xsd:restriction base="xsd:string">
          <xsd:minLength value="2"/>
          <xsd:maxLength value="3"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="streetadress">
        <xsd:restriction base="xsd:string">
          <xsd:maxLength value="30"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="zipcode">
        <xsd:restriction base="xsd:string">
          <xsd:length value="5"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="city">
        <xsd:restriction base="xsd:string">
          <xsd:maxLength value="30"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="countrycode">
        <xsd:restriction base="xsd:int">
          <xsd:totalDigits value="3"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="areacode">
        <xsd:restriction base="xsd:int">
          <xsd:totalDigits value="4"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="number">
        <xsd:restriction base="xsd:int">
          <xsd:totalDigits value="10"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="templateEntries">
        <xsd:restriction base="xsd:int">
          <xsd:minInclusive value="1"/>
          <xsd:maxInclusive value="20"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="creditCode">
        <xsd:restriction base="xsd:string">
          <xsd:length value="2"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="bokslYear">
        <xsd:restriction base="xsd:string">
          <xsd:minLength value="2"/>
          <xsd:maxLength value="2"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="templateValue">
        <xsd:restriction base="xsd:string">
          <xsd:minLength value="1"/>
          <xsd:maxLength value="14"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="lagomSequenceNr">
        <xsd:restriction base="xsd:int">
          <xsd:minInclusive value="1"/>
          <xsd:maxInclusive value="999"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="lagomDatastoreId">
        <xsd:restriction base="xsd:string">
          <xsd:minLength value="3"/>
          <xsd:maxLength value="3"/>
        </xsd:restriction>
      </xsd:simpleType>

      <!-- enumerations for this schema -->

      <xsd:simpleType groupName="repositoryaction">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="list"/>
          <xsd:enumeration value="new"/>
          <xsd:enumeration value="old"/>
        </xsd:restriction>
      </xsd:simpleType>
      
      <xsd:simpleType groupName="retrieveAction">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="list"/>
          <xsd:enumeration value="latest"/>
          <xsd:enumeration value="specific"/>          
          <xsd:minLength value="4"/>
          <xsd:maxLength value="8"/>
        </xsd:restriction>
      </xsd:simpleType>
      
      <xsd:simpleType groupName="override">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="0"/>
          <xsd:enumeration value="1"/>
          <xsd:enumeration value="2"/>
          <xsd:enumeration value="3"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="language">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="swe"/>
          <xsd:enumeration value="eng"/>
          <xsd:minLength value="3"/>
          <xsd:maxLength value="3"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="transactionType">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="1"/>
          <xsd:enumeration value="2"/>
          <xsd:enumeration value="3"/>
          <xsd:minLength value="1"/>
          <xsd:maxLength value="1"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="deliveryMedia">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="P"/>
          <xsd:enumeration value="F"/>
          <xsd:enumeration value="E"/>
          <xsd:enumeration value="S"/>
          <xsd:minLength value="1"/>
          <xsd:maxLength value="1"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="businessProduct">
        <xsd:restriction base="xsd:token">
          <xsd:minLength value="1"/>
          <xsd:maxLength value="4"/>
          <xsd:enumeration value="4"/>
          <xsd:enumeration value="91"/>
          <xsd:enumeration value="410"/>
          <xsd:enumeration value="426"/>
          <xsd:enumeration value="431"/>
          <xsd:enumeration value="432"/>
          <xsd:enumeration value="501"/>
          <xsd:enumeration value="503"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="companyProduct">
        <xsd:restriction base="xsd:token">
          <xsd:minLength value="1"/>
          <xsd:maxLength value="4"/>
          <xsd:enumeration value="4"/>
          <xsd:enumeration value="41"/>
          <xsd:enumeration value="44"/>
          <xsd:enumeration value="91"/>
          <xsd:enumeration value="410"/>
          <xsd:enumeration value="414"/>
          <xsd:enumeration value="423"/>
          <xsd:enumeration value="424"/>
          <xsd:enumeration value="426"/>
          <xsd:enumeration value="427"/>
          <xsd:enumeration value="428"/>
          <xsd:enumeration value="429"/>
          <xsd:enumeration value="430"/>
          <xsd:enumeration value="431"/>
          <xsd:enumeration value="433"/>
          <xsd:enumeration value="435"/>
          <xsd:enumeration value="4820"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="individualProduct">
        <xsd:restriction base="xsd:token">
          <xsd:minLength value="1"/>
          <xsd:maxLength value="4"/>
          <xsd:enumeration value="2"/>
          <xsd:enumeration value="3"/>
          <xsd:enumeration value="8"/>
          <xsd:enumeration value="11"/>
          <xsd:enumeration value="12"/>
          <xsd:enumeration value="13"/>
          <xsd:enumeration value="90"/>
          <xsd:enumeration value="F31"/>
          <xsd:enumeration value="R31"/>
          <xsd:enumeration value="E31"/>
          <xsd:enumeration value="E01"/>
          <xsd:enumeration value="F01"/>
          <xsd:enumeration value="R01"/>
          <xsd:enumeration value="80"/>
          <xsd:enumeration value="E81"/>
          <xsd:enumeration value="F37"/>
          <xsd:enumeration value="F07"/>
          <xsd:enumeration value="R37"/>
          <xsd:enumeration value="R07"/>
        </xsd:restriction>
      </xsd:simpleType>
      
      <xsd:simpleType groupName="seekCategoryFys">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="Fysisk person"/>
          <xsd:enumeration value="Kvinna"/>
          <xsd:enumeration value="Man"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="seekCategoryJur">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="Juridisk person"/>
          <xsd:enumeration value="AB"/>
          <xsd:enumeration value="HKB"/>
          <xsd:enumeration value="Företag"/>
          <xsd:enumeration value="Enskild firma"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="ledgerYear">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="1"/>
          <xsd:enumeration value="2"/>
          <xsd:enumeration value="3"/>
          <xsd:enumeration value="4"/>
          <xsd:enumeration value="5"/>
          <xsd:minLength value="1"/>
          <xsd:maxLength value="1"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="amountType">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="H"/>
          <xsd:enumeration value="h"/>
          <xsd:enumeration value="T"/>
          <xsd:enumeration value="t"/>
          <xsd:minLength value="1"/>
          <xsd:maxLength value="1"/>
        </xsd:restriction>
      </xsd:simpleType>

      <xsd:simpleType groupName="coverageType">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="next"/>
          <xsd:enumeration value="future"/>
          <xsd:enumeration value="incomplete"/>
        </xsd:restriction>
      </xsd:simpleType>

      <!-- Complex types for this schema -->

      <xsd:complexType groupName="bokslut">
        <xsd:attribute groupName="year" type="ucOrderRequest:bokslYear" use="optional"/>
      </xsd:complexType>
      <xsd:complexType groupName="customer">
        <xsd:sequence>
          <xsd:element groupName="userId" type="ucOrderRequest:userId" maxOccurs="1" minOccurs="1"/>
          <xsd:element groupName="password" type="ucOrderRequest:password" maxOccurs="1" minOccurs="1"/>
          <xsd:element groupName="groupName" type="ucOrderRequest:groupName" maxOccurs="1" minOccurs="0"/>
          <xsd:element groupName="changePassword" type="xsd:boolean" maxOccurs="1" minOccurs="0"/>
        </xsd:sequence>
      </xsd:complexType>

      <xsd:complexType groupName="adress">
        <xsd:sequence>
          <xsd:element groupName="streetadress" type="ucOrderRequest:streetadress" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="zipcode" type="ucOrderRequest:zipcode" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="city" type="ucOrderRequest:city" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="country" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
      </xsd:complexType>

      <xsd:complexType groupName="telephone">
        <xsd:sequence>
          <xsd:element groupName="countrycode" type="ucOrderRequest:countrycode" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="areacode" type="ucOrderRequest:areacode" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="number" type="ucOrderRequest:number" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
      </xsd:complexType>

      <xsd:complexType groupName="templateIncome">
        <xsd:attribute groupName="type" type="ucOrderRequest:amountType" use="optional"/>
        <xsd:attribute groupName="value" type="ucOrderRequest:income" use="required"/>
      </xsd:complexType>

      <xsd:complexType groupName="template">
        <xsd:sequence>
          <xsd:element groupName="income" type="ucOrderRequest:templateIncome" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="coObject" type="ucOrderRequest:objectRef" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="coObjectIncome" type="ucOrderRequest:income" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="templateParams" type="ucOrderRequest:templateParams" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute groupName="level" type="xsd:string" use="required"/>
      </xsd:complexType>

      <xsd:complexType groupName="templateParams">
        <xsd:sequence>
          <xsd:element groupName="templateparam" type="ucOrderRequest:templateparam" minOccurs="0" maxOccurs="20"/>
        </xsd:sequence>
      </xsd:complexType>

      <xsd:complexType groupName="templateparam">
        <xsd:attribute groupName="level" type="ucOrderRequest:templateEntries" use="required"/>
        <xsd:attribute groupName="value" type="ucOrderRequest:templateValue" use="required"/>
      </xsd:complexType>

      <xsd:complexType groupName="coObjectReference">
        <xsd:sequence>
          <xsd:element groupName="objectReference" type="ucOrderRequest:objectRef"/>
          <xsd:element groupName="income" type="ucOrderRequest:income"/>
        </xsd:sequence>
      </xsd:complexType>

      <xsd:complexType groupName="emailId">
        <xsd:simpleContent>
          <xsd:extension base="xsd:string">
            <xsd:attribute groupName="update" type="xsd:string" use="optional"/>
          </xsd:extension>
        </xsd:simpleContent>
      </xsd:complexType>

      <xsd:complexType groupName="reportQuery">
      	<xsd:sequence>
      		<xsd:element groupName="object" type="ucOrderRequest:objectRef" minOccurs="1" maxOccurs="1"/>
      		<xsd:element groupName="orderedBy" type="ucOrderRequest:groupName" minOccurs="0" maxOccurs="1"/>
      		<xsd:element groupName="reference" type="ucOrderRequest:referenceName" minOccurs="0" maxOccurs="1"/>
      		<xsd:element groupName="override" type="ucOrderRequest:override" minOccurs="0" maxOccurs="1"/>
      		<xsd:element groupName="creditSeeked" type="ucOrderRequest:creditseekAmount" minOccurs="0" maxOccurs="1"/>
      		<xsd:element groupName="template" type="ucOrderRequest:template" minOccurs="0" maxOccurs="1"/>
      	</xsd:sequence>
      	<xsd:attribute groupName="xmlReply" type="xsd:boolean" use="required"/>
      	<xsd:attribute groupName="htmlReply" type="xsd:boolean" use="required"/>
      	<xsd:attribute groupName="reviewReply" type="xsd:boolean" use="optional"/>
      	<xsd:attribute groupName="pdfReply" type="xsd:boolean" use="optional"/>
      	<xsd:attribute groupName="extendedDetails" type="xsd:boolean" use="optional"/>
      	<xsd:attribute groupName="lang" type="ucOrderRequest:language" use="optional"/>
      </xsd:complexType>

      <xsd:complexType groupName="annualQuery">
      	<xsd:sequence>
      		<xsd:element groupName="object" type="ucOrderRequest:objectRef" minOccurs="1" maxOccurs="1"/>
			<xsd:element groupName="reportYear" type="ucOrderRequest:annualReportYear" minOccurs="0" maxOccurs="1"/>
      	</xsd:sequence>
      </xsd:complexType>

      <xsd:complexType groupName="certificates">
        <xsd:attribute groupName="order" type="xsd:string" use="optional"/>
      </xsd:complexType>

      <xsd:complexType groupName="credits">
        <xsd:attribute groupName="order" type="xsd:string" use="optional"/>
        <xsd:attribute groupName="stock" type="ucOrderRequest:creditCode" use="optional"/>
      </xsd:complexType>

      <xsd:complexType groupName="coverage">
        <xsd:sequence>
          <xsd:element groupName="certificates" type="ucOrderRequest:certificates"/>
          <xsd:element groupName="credits" type="ucOrderRequest:credits"/>
        </xsd:sequence>
      </xsd:complexType>

      <xsd:complexType groupName="accountsCoverage">
        <xsd:attribute groupName="type" type="ucOrderRequest:coverageType" use="optional"/>
      </xsd:complexType>

      <xsd:complexType groupName="originalDocuments">
        <xsd:attribute groupName="altCertificate" type="xsd:boolean" use="optional"/>
        <xsd:attribute groupName="articlesOfAssociation" type="xsd:boolean" use="optional"/>
        <xsd:attribute groupName="certificate" type="xsd:boolean" use="optional"/>
        <xsd:attribute groupName="shareholdersMeetingProtocol" type="xsd:boolean" use="optional"/>
      </xsd:complexType>
      <xsd:complexType groupName="seekFysiker">
        <xsd:sequence>
          <xsd:element groupName="seekName" type="ucOrderRequest:seekName" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="adress" type="ucOrderRequest:adress" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="seekCategoryFys" type="ucOrderRequest:seekCategoryFys" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute groupName="xmlReply" type="xsd:boolean" use="required"/>
        <xsd:attribute groupName="htmlReply" type="xsd:boolean" use="required"/>
        <xsd:attribute groupName="reviewReply" type="xsd:boolean" use="optional"/>
      </xsd:complexType>

      <xsd:complexType groupName="seekJuridiker">
        <xsd:sequence>
          <xsd:element groupName="seekName" type="ucOrderRequest:seekName" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="adress" type="ucOrderRequest:adress" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="telephone" type="ucOrderRequest:telephone" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="seekCategoryJur" type="ucOrderRequest:seekCategoryJur" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute groupName="xmlReply" type="xsd:boolean" use="required"/>
        <xsd:attribute groupName="htmlReply" type="xsd:boolean" use="required"/>
        <xsd:attribute groupName="reviewReply" type="xsd:boolean" use="optional"/>
      </xsd:complexType>

      <xsd:complexType groupName="extras">
        <xsd:sequence>
          <xsd:element groupName="telefax" type="ucOrderRequest:telephone" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="emailId" type="ucOrderRequest:emailName" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="object" type="ucOrderRequest:objectRef" minOccurs="0" maxOccurs="1"/>
          <xsd:element groupName="bokslut" type="ucOrderRequest:bokslut" minOccurs="1" maxOccurs="5"/>
          <xsd:element groupName="coverage" type="ucOrderRequest:coverage"/>
          <xsd:element groupName="originalDocuments" type="ucOrderRequest:originalDocuments"/>
          <xsd:element groupName="accountsCoverage" type="ucOrderRequest:accountsCoverage"/>
        </xsd:sequence>
        <xsd:attribute groupName="deliveryForm" type="ucOrderRequest:deliveryMedia" use="optional"/>
      </xsd:complexType>

    </xsd:schema>

    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ucOrderReply="http://www.uc.se/schemas/ucOrderReply/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://www.uc.se/schemas/ucOrderReply/">

      <xsd:element groupName="ucReply">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="ucOrderReply:status" minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="ucOrderReply:ucReport" minOccurs="0" maxOccurs="unbounded"/>
          </xsd:sequence>
          <xsd:attribute groupName="version" type="xsd:string" use="optional"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="ucReport">
        <xsd:complexType>
          <xsd:sequence>
          	<xsd:element ref="ucOrderReply:xmlReply" minOccurs="0" maxOccurs="1"/>
          	<xsd:element ref="ucOrderReply:htmlReply" minOccurs="0" maxOccurs="1"/>
          	<xsd:element ref="ucOrderReply:reviewReply" minOccurs="0" maxOccurs="1"/>
          	<xsd:element groupName="pdfReply" type="xsd:base64Binary" minOccurs="0" maxOccurs="1"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="status">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="ucOrderReply:message" minOccurs="0" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:attribute groupName="result" type="xsd:string"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="message">
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute groupName="level" type="xsd:string" use="required"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="xmlReply">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="ucOrderReply:reports" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element ref="ucOrderReply:lagomlista" minOccurs="0" maxOccurs="1"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="reports">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="ucOrderReply:report" minOccurs="1" maxOccurs="unbounded"/>
          </xsd:sequence>
          <xsd:attribute groupName="lang" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="report">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="1" ref="ucOrderReply:group"/>
          </xsd:sequence>
          <xsd:attribute groupName="level" type="xsd:string" use="required"/>
          <xsd:attribute groupName="groupName" type="xsd:string" use="required"/>
          <xsd:attribute groupName="styp" type="xsd:string" use="required"/>
          <xsd:attribute groupName="index" type="xsd:string" use="required"/>
          <xsd:attribute groupName="lagomid" type="xsd:string" use="optional"/>
          <xsd:attribute groupName="lagomlopnr" type="xsd:string" use="optional"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="lagomlista">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="1" ref="ucOrderReply:group"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="group">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" ref="ucOrderReply:term"/>
          </xsd:sequence>
          <xsd:attribute groupName="level" type="xsd:string" use="required"/>
          <xsd:attribute groupName="index" type="xsd:string" use="required"/>
          <xsd:attribute groupName="key" type="xsd:string" use="optional"/>
          <xsd:attribute groupName="groupName" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="term">
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute groupName="level" type="xsd:string" use="required"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>

      <xsd:element groupName="htmlReply" type="xsd:string"/>
      <xsd:element groupName="reviewReply" type="xsd:string"/>

    </xsd:schema>

  </wsdl:types>

  <wsdl:message groupName="businessReport">
    <wsdl:part groupName="businessReportRequest" element="s0:businessReport"/>
  </wsdl:message>
  <wsdl:message groupName="companyReport">
    <wsdl:part groupName="companyReportRequest" element="s0:companyReport"/>
  </wsdl:message>
  <wsdl:message groupName="individualReport">
    <wsdl:part groupName="individualReportRequest" element="s0:individualReport"/>
  </wsdl:message>
  <wsdl:message groupName="identityCheck">
    <wsdl:part groupName="identityCheckRequest" element="s0:identityCheck"/>
  </wsdl:message>
  <wsdl:message groupName="identitySeekFys">
    <wsdl:part groupName="identitySeekFysRequest" element="s0:identitySeekFys"/>
  </wsdl:message>
  <wsdl:message groupName="identitySeekJur">
    <wsdl:part groupName="identitySeekJurRequest" element="s0:identitySeekJur"/>
  </wsdl:message>
  <wsdl:message groupName="retrieveLagomReport">
    <wsdl:part groupName="retrieveLagomReportRequest" element="s0:retrieveLagomReport"/>
  </wsdl:message>
  <wsdl:message groupName="retrieveAnnualReport">
    <wsdl:part groupName="retrieveAnnualReportRequest" element="s0:retrieveAnnualReport"/>
  </wsdl:message>
  <wsdl:message groupName="ping">
	<wsdl:part groupName="pingRequest" element="s0:ping"/>
  </wsdl:message>
  <wsdl:message groupName="ucReportResponse">
    <wsdl:part groupName="ucReportResponse" element="s1:ucReply"/>
  </wsdl:message>
  
  <wsdl:portType groupName="ucOrders">
    <wsdl:operation groupName="businessReport">
      <wsdl:input message="tns:businessReport"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="companyReport">
      <wsdl:input message="tns:companyReport"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="individualReport">
      <wsdl:input message="tns:individualReport"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="identityCheck">
      <wsdl:input message="tns:identityCheck"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="identitySeekFys">
      <wsdl:input message="tns:identitySeekFys"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="identitySeekJur">
      <wsdl:input message="tns:identitySeekJur"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="retrieveLagomReport">
      <wsdl:input message="tns:retrieveLagomReport"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="retrieveAnnualReport">
      <wsdl:input message="tns:retrieveAnnualReport"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    <wsdl:operation groupName="ping">
      <wsdl:input message="tns:ping"/>
      <wsdl:output message="tns:ucReportResponse"/>
    </wsdl:operation>
    
  </wsdl:portType>

  <wsdl:binding groupName="ucOrderBinding" type="tns:ucOrders">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation groupName="businessReport">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/businessReport" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="companyReport">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/companyReport" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="individualReport">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/individualReport" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="identityCheck">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/identityCheck" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="identitySeekFys">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/identitySeekFys" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="identitySeekJur">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/identitySeekJur" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="retrieveLagomReport">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/retrieveLagomReport" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="retrieveAnnualReport">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/retrieveAnnualReport" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation groupName="ping">
      <soap:operation soapAction="http://www.uc.se/ws/ucOrders/ping" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service groupName="UCOrderService">
    <wsdl:port groupName="ucOrders2" binding="tns:ucOrderBinding">
      <!--<soap:address location="http://www1.uc.se:80/UCSoapWeb/services/ucOrders2"/>-->
      <soap:address location="https://www1.uc.se/UCSoapWeb/services/ucOrders2"/>
    </wsdl:port>
  </wsdl:service>


</wsdl:definitions>