
package uc_webservice_test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ucOrders", targetNamespace = "http://webservices.uc.se/UCOrders/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UcOrders {


    /**
     * 
     * @param businessReportRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/businessReport")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply businessReport(
        @WebParam(name = "businessReport", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "businessReportRequest")
        BusinessReport businessReportRequest);

    /**
     * 
     * @param companyReportRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/companyReport")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply companyReport(
        @WebParam(name = "companyReport", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "companyReportRequest")
        CompanyReport companyReportRequest);

    /**
     * 
     * @param individualReportRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/individualReport")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply individualReport(
        @WebParam(name = "individualReport", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "individualReportRequest")
        IndividualReport individualReportRequest);

    /**
     * 
     * @param identityCheckRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/identityCheck")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply identityCheck(
        @WebParam(name = "identityCheck", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "identityCheckRequest")
        IdentityCheck identityCheckRequest);

    /**
     * 
     * @param identitySeekFysRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/identitySeekFys")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply identitySeekFys(
        @WebParam(name = "identitySeekFys", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "identitySeekFysRequest")
        IdentitySeekFys identitySeekFysRequest);

    /**
     * 
     * @param identitySeekJurRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/identitySeekJur")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply identitySeekJur(
        @WebParam(name = "identitySeekJur", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "identitySeekJurRequest")
        IdentitySeekJur identitySeekJurRequest);

    /**
     * 
     * @param retrieveLagomReportRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/retrieveLagomReport")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply retrieveLagomReport(
        @WebParam(name = "retrieveLagomReport", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "retrieveLagomReportRequest")
        RetrieveLagomReport retrieveLagomReportRequest);

    /**
     * 
     * @param retrieveAnnualReportRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/retrieveAnnualReport")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply retrieveAnnualReport(
        @WebParam(name = "retrieveAnnualReport", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "retrieveAnnualReportRequest")
        RetrieveAnnualReport retrieveAnnualReportRequest);

    /**
     * 
     * @param pingRequest
     * @return
     *     returns uc_webservice_test.UcReply
     */
    @WebMethod(action = "http://www.uc.se/ws/ucOrders/ping")
    @WebResult(name = "ucReply", targetNamespace = "http://www.uc.se/schemas/ucOrderReply/", partName = "ucReportResponse")
    public UcReply ping(
        @WebParam(name = "ping", targetNamespace = "http://www.uc.se/schemas/ucOrderRequest/", partName = "pingRequest")
        Ping pingRequest);

}
